#### Update Handlers to use ResponseError

```diff
+import {ResponseError} from 'fusion-plugin-rpc';

const handlers = {
  test(args) {
-   throw new Error('test');
+   const e = new ResponseError('test');
+   e.code = 'ERRTEST';
+   e.meta = {custom: 'metadata'};
+   throw e;
  }
}
```

If you were previously relying on errors propogating up from libraries, you should wrap your usage of the library in a
try catch and manually throw a ResponseError. For example:

```diff
const handlers = {
  test(args) {
-   await doThing();
-   await doOtherThing();
+   try {
+     await doThing();
+     await doOtherThing();
+   } catch(err) {
+     const e = new ResponseError(err.message);
+     e.code = 'ERRDOTHING';
+     e.meta = {custom: 'metadata'};
+     throw e;
+   }
  }
}
```
